routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@home')->name('home');
Route::get('/meetings/table', 'MeetingTableController')->name('meetings.table');
Route::get('/settings/edit', 'SettingsController@edit')->name('settings.edit');

Route::put('/settings', 'SettingsController@update')->name('settings.update');

Route::prefix('remind')->group(function() {
    Route::get('access_tokens', 'RemindController@accessTokensCreate')->name('remind.access_tokens.create');
    Route::get('classes', 'RemindController@classes');
    Route::get('user', 'RemindController@user')->name('remind.user');

    Route::post('access_tokens', 'RemindController@accessTokens')->name('remind.access_tokens.store');
    Route::post('classes/invitations', 'RemindController@classesInvitations')->name('remind.classes.invitations.store');
});

Route::resource('events', 'EventController');
Route::resource('meetings', 'MeetingController');
Route::resource('members', 'MemberController');
Route::resource('settings', 'SettingsController', ['only' =>
    [
        'index'
    ]
]);
Route::resource('users', 'UserController');

app/Meeting.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Meeting extends Model
{
    protected $fillable = ['date_time', 'information'];

    public function members()
    {
        return $this->belongsToMany('App\Member');
    }

    public function missing_members() {
        return $this->hasMany('App\MissingMember');
    }
}

app/Http/Controllers/Api/MeetingController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Meeting;
use App\Services\MeetingService;
use Illuminate\Http\Request;

class MeetingController extends Controller
{
    protected $meetings;

    public function __construct(MeetingService $meetings)
    {
        $this->meetings = $meetings;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return $this->meetings->index();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        return $this->meetings->store($request);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Meeting  $meeting
     * @return \Illuminate\Http\Response
     */
    public function show(Meeting $meeting)
    {
        return $meeting;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Meeting  $meeting
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Meeting $meeting)
    {
        return $this->meetings->update($request, $meeting);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Meeting  $meeting
     * @return \Illuminate\Http\Response
     */
    public function destroy(Meeting $meeting)
    {
        $this->meetings->destroy($meeting);
        return [
            'message' => 'Meeting deleted successfully.'
        ];
    }
}

app/Http/Controllers/MeetingController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Log;
use Illuminate\Http\Request;

use App\MissingMember;
use App\Member;
use App\Meeting;
use App\Services\MeetingService;

class MeetingController extends Controller
{
    protected $meetings;

    public function __construct(MeetingService $meetings)
    {
        $this->middleware('auth');
        $this->meetings = $meetings;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('meeting/index', [
            'meetings' => $this->meetings->index()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create', Meeting::class);
        return view('meeting.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $member = $this->meetings->store($request);
        return view('meeting.index', [
            'meetings' => $this->meetings->index()
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Meeting  $meeting
     * @return \Illuminate\Http\Response
     */
    public function show(Meeting $meeting)
    {
        return view('meeting.show', [
            'meeting' => $meeting
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Meeting  $meeting
     * @return \Illuminate\Http\Response
     */
    public function edit(Meeting $meeting)
    {
        $this->authorize('update', $meeting);
        return view('meeting.edit', [
            'meeting' => $meeting,
            'members' => Member::all()
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Meeting  $meeting
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Meeting $meeting)
    {
        $response = $this->meetings->update($request, $meeting);
        return view('meeting.show', [
            'meeting' => $meeting
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Meeting  $meeting
     * @return \Illuminate\Http\Response
     */
    public function destroy(Meeting $meeting)
    {
        $this->meetings->destroy($meeting);
        return redirect()->route('meetings.index');
    }
}

resources/views/meeting/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Create Meeting</div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST" action="{{ route('meetings.store') }}">
                        {{ csrf_field() }}

                        <date-time label="Date & Time" name="date_time"></date-time>
                        <text-area label="Information" name="information"></text-area>

                        <submit-button btn-style="btn-success" label="Create"></submit-button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/meeting/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Edit Meeting</div>
                <div class="panel-content">
                    <p><strong>Note:</strong> The JSON input should only be used when meeting upload has malfunctioned.</p>
                    <form class="form-horizontal" role="form" method="POST" action="{{ route('meetings.update', $meeting->id) }}">
                        {{ csrf_field() }}
                        {{ method_field('PUT') }}
                        <text-area label="Meeting JSON" name="meeting_json"></text-area>

                        <date-time label="Date & Time" name="date_time" value="{{ $meeting->date_time }}"></date-time>
                        <text-area label="Information" name="information" value="{{ $meeting->information }}"></text-area>

                        <data-list-input datalist="memberlist"></data-list-input>

                        <datalist id="memberlist">
                        @foreach ($members as $member)
                            <option value="{{$member->id}}">{{ $member->first . ' ' . $member->last }}</option>
                        @endforeach
                        </datalist>

                        <submit-button btn-style="btn-primary" label="Update"></submit-button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/meeting/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Meetings</div>
                <div class="panel-body">
                    <table id="table" style="width: 100%;">
                        <thead>
                            <tr>
                                <th style="width: 20%;">Date</th>
                                <th style="width: 75%;">Information</th>
                                <th style="width: 5%;">More</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($meetings as $meeting)
                                <tr>
                                    <td>{{$meeting->date_time}}</td>
                                    <td>{{$meeting->information}}</td>
                                    <td>
                                        <div class="dropdown">
                                            <span class="glyphicon glyphicon-option-horizontal dropdown-toggle" data-toggle="dropdown">
                                            </span>
                                            <ul class="dropdown-menu">
                                                <li><a href="{{ route('meetings.show', $meeting->id) }}">View Details</a></li>
                                                <li><a href="{{ route('meetings.edit', $meeting->id) }}">Edit</a></li>
                                                <li>
                                                    <a href="{{ route('meetings.update', $meeting->id) }}"
                                                    onclick="event.preventDefault();
                                                            document.getElementById('duplicate-form').action = '{{ route('meetings.update', $meeting->id) }}';
                                                            document.getElementById('duplicate-form').submit();">Fix Duplicate Members</a>
                                                </li>
                                                <li>
                                                    <a href="{{ route('meetings.update', $meeting->id) }}"
                                                    onclick="event.preventDefault();
                                                            document.getElementById('missing-form').action = '{{ route('meetings.update', $meeting->id) }}';
                                                            document.getElementById('missing-form').submit();">Fix Missing Members</a>
                                                </li>
                                            </ul>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <form id="duplicate-form" method="POST" style="display: none;">
        {{ csrf_field() }}
        {{ method_field('PUT') }}
        <input type="hidden" name="duplicate">
    </form>
    <form id="missing-form" method="POST" style="display: none;">
        {{ csrf_field() }}
        {{ method_field('PUT') }}
        <input type="hidden" name="missing">
    </form>
</div>
@endsection

@section('scripts')
<script>
    $(document).ready(() => {
        $('#table').DataTable();
    });
</script>
@endsection

resources/views/meeting/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Meeting on {{ $meeting->date_time }} - Information</div>
                <div class="panel-body">
                    <p>{{ $meeting->information }}</p>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">Meeting Attendance</div>
                <div class="panel-body">
                    <table id="table" style="width: 100%;">
                        <thead>
                            <tr>
                                <th style="width: 5%">ID</th>
                                <th style="width: 45%">First Name</th>
                                <th style="width: 45%">Last Name</th>
                                <th style="width: 5%">More</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($meeting->members as $member)
                            <tr>
                                <td>{{ $member->id }}</td>
                                <td>{{ $member->first }}</td>
                                <td>{{ $member->last }}</td>
                                <td>
                                    <div class="dropdown">
                                        <span class="glyphicon glyphicon-option-horizontal dropdown-toggle" data-toggle="dropdown">
                                        </span>
                                        <ul class="dropdown-menu">
                                            <li><a href="{{ route('members.show', $member->id) }}">View Member</a></li>
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">Missing Members</div>
                <div class="panel-body">
                    <table id="table2">
                        <thead>
                            <tr>
                                <th style="width: 100%;">ID</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($meeting->missing_members as $missing)
                            <tr>
                                <td>{{$missing->id}}</td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
<script>
    $(document).ready(() => {
        console.log("Initializing DataTables...");
        $('#table').DataTable();
        $('#table2').DataTable();
    });
</script>
@endsection

resources/views/meeting/table.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Meetings Table</div>
                <div class="panel-body">
                    <table id="table">
                        <thead>
                            <tr>
                                <th style="width: 10%;">Member</th>
                                @foreach($meetings as $meeting)
                                <th style="width: {{90 / $meetings->count()}}%;">{{$meeting->date_time}}</th>
                                @endforeach
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($members as $member)
                               <tr>
                                    <td>{{ $member->first . ' ' . $member->last }}</td>
                                    @foreach($meetings as $meeting)
                                        @if($member->meetings()->find($meeting->id))
                                            <td>X</td>
                                        @else
                                            <td></td>
                                        @endif
                                    @endforeach
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
<script>
    $(document).ready(() => {
        $('#table').DataTable({
            fixedHeader: true
        });
    });
</script>
@endsection