routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@home')->name('home');
Route::get('/meetings/table', 'MeetingTableController')->name('meetings.table');
Route::get('/settings/edit', 'SettingsController@edit')->name('settings.edit');

Route::put('/settings', 'SettingsController@update')->name('settings.update');

Route::prefix('remind')->group(function() {
    Route::get('access_tokens', 'RemindController@accessTokensCreate')->name('remind.access_tokens.create');
    Route::get('classes', 'RemindController@classes');
    Route::get('user', 'RemindController@user')->name('remind.user');

    Route::post('access_tokens', 'RemindController@accessTokens')->name('remind.access_tokens.store');
    Route::post('classes/invitations', 'RemindController@classesInvitations')->name('remind.classes.invitations.store');
});

Route::resource('events', 'EventController');
Route::resource('meetings', 'MeetingController');
Route::resource('members', 'MemberController');
Route::resource('settings', 'SettingsController', ['only' =>
    [
        'index'
    ]
]);
Route::resource('users', 'UserController');

app/Member.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Member extends Model
{
    protected $fillable = [
        'id', 'first', 'last', 'nickname', 'suffix', 'email', 'address1', 'address2', 'city', 'country',
        'state', 'postal', 'graduation', 'phone', 'birth', 'gender', 'secondary_id'
    ];

    public $incrementing = false;

    public function user()
    {
        return $this->hasOne('App\User');
    }

    public function events()
    {
        return $this->belongsToMany('App\Event');
    }

    public function meetings()
    {
        return $this->belongsToMany('App\Meeting');
    }

    public function officer()
    {
        return $this->hasOne('App\Officer');
    }
}

app/Http/Controllers/Api/MemberController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Member;
use App\Services\MemberService;

use Illuminate\Http\Request;

class MemberController extends Controller
{
    public function __construct(MemberService $members)
    {
        $this->members = $members;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      return $this->members->index();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        return $this->members->store($request);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Member  $member
     * @return \Illuminate\Http\Response
     */
    public function show(Member $member)
    {
        return $member;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Member  $member
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Member $member)
    {
        return $this->members->update($request, $member);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Member  $member
     * @return \Illuminate\Http\Response
     */
    public function destroy(Member $member)
    {
        $response = $this->members->destroy($member);
        if ($response === 403) {
            return response()->json([
                'error' => 'You cannot delete your own member instance.'
            ], 403);
        } else {
            return [
                'message' => 'Member deleted successfully.'
            ];
        }
    }
}

app/Http/Controllers/MemberController.php
<?php

namespace App\Http\Controllers;

use App\Member;
use App\Services\MemberService;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Validator;

class MemberController extends Controller
{
    protected $members;

    public function __construct(MemberService $members) {
        $this->middleware('auth');
        $this->members = $members;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('member.index', [
            'members' => $this->members->index()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create', Member::class);
        return view('member.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $member = $this->members->store($request);

        return view('member.index', [
            'members' => Member::all()
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Member  $member
     * @return \Illuminate\Http\Response
     */
    public function show(Member $member)
    {
        return view('member.show', [
            'member' => $member
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Member  $member
     * @return \Illuminate\Http\Response
     */
    public function edit(Member $member)
    {
        $this->authorize('update', $member);
        return view('member.edit', [
            'member' => $member
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Member  $member
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Member $member)
    {
        return view('member.show', [
            'member' => $this->members->update($request, $member)
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Member  $member
     * @return \Illuminate\Http\Response
     */
    public function destroy(Member $member)
    {
        $response = $this->members->destroy($member);
        if ($response === 403) {
            return back();
        } else {
            return redirect()->route('members.index');
        }
    }
}

resources/views/member/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Add Member</div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST" action="{{ route('members.store') }}">
                        {{ csrf_field() }}

                        <text-input label="ID*" name="id" value="{{ old('id') }}" required
                            @if ($errors->has('id'))
                                error="{{$errors->first('id')}}"
                            @endif></text-input>
                        <text-input label="First Name*" name="first" value="{{ old('first') }}" required
                            @if ($errors->has('first'))
                                error="{{$errors->first('first')}}"
                            @endif></text-input>
                        <text-input label="Last Name*" name="last" value="{{ old('last') }}" required
                            @if ($errors->has('last'))
                                error="{{$errors->first('last')}}"
                            @endif></text-input>
                        <text-input label="Nickname" name="nickname" value="{{ old('nickname') }}"></text-input>
                        <text-input label="Suffix" name="suffix" value="{{ old('suffix') }}"></text-input>
                        <text-input label="Email*" name="email" value="{{ old('email') }}" required
                            @if ($errors->has('email'))
                                error="{{$errors->first('email')}}")
                            @endif> </text-input>
                        <text-input label="Address" name="address1" value="{{ old('address1') }}"></text-input>
                        <text-input label="Address 2" name="address2" value="{{ old('address2') }}"></text-input>
                        <text-input label="City" name="city" value="{{ old('city') }}"></text-input>
                        <text-input label="State" name="state" value="{{ old('state') }}"></text-input>
                        <text-input label="Country" name="country" value="{{ old('country') }}"></text-input>
                        <text-input label="ZIP Code" name="postal" value="{{ old('postal') }}"></text-input>
                        <text-input label="Graduation Year*" name="graduation" value="{{ old('graduation') }}" required
                            @if ($errors->has('graduation'))
                                error="{{$errors->first('graduation')}}"
                            @endif></text-input>
                        <text-input label="Phone Number*" name="phone" value="{{ old('phone') }}"
                            @if ($errors->has('phone'))
                                error="{{$errors->first('phone')}}"
                            @endif></text-input>
                        <date-input label="Birth Date" name="birth" value="{{ old('birth') }}"></date-input>
                        <text-input label="Gender" name="gender" value="{{ old('gender') }}"></text-input>
                        <text-input label="Secondary ID" name="secondary_id" value="{{ old('secondary_id') }}"></text-input>
                        <submit-button btn-style="btn-success" label="Create"></submit-button>
                        <div class="col-md-offset-4 col-md-8">
                            <strong style="color: red;">* = Required</strong>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/member/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Add Member</div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST" action="{{ route('members.update', $member->id) }}">
                        {{ csrf_field() }}
                        {{ method_field('PUT') }}

                        <text-input label="ID*" name="id" value="{{ $errors->has('id') ? old('id') : $member->id }}" required
                            @if ($errors->has('id'))
                                error="{{$errors->first('id')}}"
                            @endif></text-input>
                        <text-input label="First Name*" name="first" value="{{ $errors->has('first') ? old('first') : $member->first }}" required
                            @if ($errors->has('first'))
                                error="{{$errors->first('first')}}"
                            @endif></text-input>
                        <text-input label="Last Name*" name="last" value="{{ $errors->has('last') ? old('last') : $member->last }}" required
                            @if ($errors->has('last'))
                                error="{{$errors->first('last')}}"
                            @endif></text-input>
                        <text-input label="Nickname" name="nickname" value="{{ $errors->has('nickname') ? old('nickname') : $member->nickname }}"></text-input>
                        <text-input label="Suffix" name="suffix" value="{{ $errors->has('suffix') ? old('suffix') : $member->suffix }}"></text-input>
                        <text-input label="Email*" name="email" value="{{ $errors->has('email') ? old('email') : $member->email }}" required
                            @if ($errors->has('email'))
                                error="{{$errors->first('email')}}")
                            @endif> </text-input>
                        <text-input label="Address" name="address1" value="{{ $errors->has('address1') ? old('address1') : $member->address1 }}"></text-input>
                        <text-input label="Address 2" name="address2" value="{{ $errors->has('address2') ? old('address2') : $member->address2 }}"></text-input>
                        <text-input label="City" name="city" value="{{ $errors->has('city') ? old('city') : $member->city }}"></text-input>
                        <text-input label="State" name="state" value="{{ $errors->has('state') ? old('state') : $member->state }}"></text-input>
                        <text-input label="Country" name="country" value="{{ $errors->has('country') ? old('country') : $member->country }}"></text-input>
                        <text-input label="ZIP Code" name="postal" value="{{ $errors->has('postal') ? old('postal') : $member->postal }}"></text-input>
                        <text-input label="Graduation Year*" name="graduation" value="{{ $errors->has('graduation') ? old('graduation') : $member->graduation }}" required
                            @if ($errors->has('graduation'))
                                error="{{$errors->first('graduation')}}"
                            @endif></text-input>
                        <text-input label="Phone Number*" name="phone" value="{{ $errors->has('phone') ? old('phone') : $member->phone }}"
                            @if ($errors->has('phone'))
                                error="{{$errors->first('phone')}}"
                            @endif></text-input>
                        <date-input label="Birth Date" name="birth" value="{{ $errors->has('birth') ? old('birth') : $member->birth }}"></date-input>
                        <text-input label="Gender" name="gender" value="{{ $errors->has('gender') ? old('gender') : $member->gender }}"></text-input>
                        <text-input label="Secondary ID" name="secondary_id" value="{{ $errors->has('secondary_id') ? old('secondary_id') : $member->secondary_id }}"></text-input>
                        <submit-button btn-style="btn-primary" label="Update"></submit-button>
                        <div class="col-md-offset-4 col-md-8">
                            <strong style="color: red;">* = Required</strong>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/member/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Members</div>
                <div class="panel-body">
                    @switch (Session::get('type'))
                        @case ('delete')
                            <div class="alert alert-success">
                                User deleted successfully!
                            </div>
                            @break
                        @case ('self')
                            <div class="alert alert-danger">
                                You cannot delete yourself from the member list.
                            </div>
                            @break
                    @endswitch

                    @isset($status)
                        <div class="alert alert-success">
                            User added successfully! <a href="{{ route('members.create') }}" class="alert-link">Add another?</a>
                        </div>
                    @endisset

                    <table id="table" style="width: 100%;">
                        <thead>
                            <tr>
                                <th style="width: 5%;">ID</th>
                                <th style="width: 35%;">First Name</th>
                                <th style="width: 35%;">Last Name</th>
                                <th style="width: 20%;">Date Added</th>
                                <th style="width: 5%;">More</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($members as $member)
                                <tr>
                                    <td>{{$member->id}}</td>
                                    <td>{{$member->first}}</td>
                                    <td>{{$member->last}}</td>
                                    <td data-order="{{$member->created_at}}">{{$member->created_at->format('d M Y, h:i A')}}</td>
                                    <td>
                                        <div class="dropdown">
                                            <span class="glyphicon glyphicon-option-horizontal dropdown-toggle" data-toggle="dropdown">
                                            </span>
                                            <ul class="dropdown-menu">
                                                <li><a href="{{ route('members.show', $member->id) }}">View Member</a></li>
                                                @auth
                                                <li><a href="{{ route('members.edit', $member->id) }}">Edit Member</a></li>
                                                <li>
                                                    <a href="{{ route('remind.classes.invitations.store') }}"
                                                        onclick="event.preventDefault();
                                                                 document.getElementById('memberID').value='{{$member->id}}';
                                                                 document.getElementById('classID').value=prompt('Class ID');
                                                                 document.getElementById('invite-form').submit();">
                                                        Send Remind Invite
                                                    </a>

                                                    <form id="invite-form" action="{{ route('remind.classes.invitations.store') }}"
                                                        method="POST" style="display: none;">
                                                        {{ csrf_field() }}
                                                        <text-input name="memberID"></text-input>
                                                        <text-input name="classID"></text-input>
                                                    </form>
                                                </li>
                                                <li>
                                                    <a onclick="event.preventDefault();
                                                                document.getElementById('delete-form').action =
                                                                document.getElementById('delete-link').href =
                                                                '{{ route('members.destroy', $member->id) }}';"
                                                        data-toggle="modal" data-target="#deleteModal" style="cursor: pointer;">
                                                        Delete Member
                                                    </a>
                                                </li>
                                                @endauth
                                            </ul>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div id="deleteModal" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Delete Member</h4>
                </div>
                <div class="modal-body">
                    <p>Are you <strong>sure</strong> you want to delete this user?</p>
                    <form id="delete-form" method="POST" style="display: none;">
                        {{ csrf_field() }}
                        {{ method_field('DELETE') }}
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                    <a href="{{ route('members.create') }}" id="delete-link" class="btn btn-danger"
                        onclick="event.preventDefault();
                                document.getElementById('delete-form').submit();">
                        Delete Member
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
<script>
    $(document).ready(() => {
        $('#table').DataTable();
    });
</script>
@endsection

resources/views/member/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Member Information for {{ $member->first }} {{ $member->last }}</div>
                <div class="panel-body">
                    <p><strong>Name: </strong>{{$member->first}} {{$member->last}}</p>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection