routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@home')->name('home');
Route::get('/meetings/table', 'MeetingTableController')->name('meetings.table');
Route::get('/settings/edit', 'SettingsController@edit')->name('settings.edit');

Route::put('/settings', 'SettingsController@update')->name('settings.update');

Route::prefix('remind')->group(function() {
    Route::get('access_tokens', 'RemindController@accessTokensCreate')->name('remind.access_tokens.create');
    Route::get('classes', 'RemindController@classes');
    Route::get('user', 'RemindController@user')->name('remind.user');

    Route::post('access_tokens', 'RemindController@accessTokens')->name('remind.access_tokens.store');
    Route::post('classes/invitations', 'RemindController@classesInvitations')->name('remind.classes.invitations.store');
});

Route::resource('events', 'EventController');
Route::resource('meetings', 'MeetingController');
Route::resource('members', 'MemberController');
Route::resource('settings', 'SettingsController', ['only' =>
    [
        'index'
    ]
]);
Route::resource('users', 'UserController');

app/Event.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Event extends Model
{
    protected $fillable = [
        'name', 'date', 'start', 'end', 'hours', 'officer_id'
    ];
    //
    public function members() {
        return $this->belongsToMany('App\Member');
    }
}

app/Http/Controllers/EventController.php
<?php

namespace App\Http\Controllers;

use App\Event;
use App\Member;
use App\Officer;
use Illuminate\Http\Request;

class EventController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $events = Event::all();
        return view('event/index', ['events' => $events]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create', Event::class);
        return view('event/create', [
            'officers' => Officer::all()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->authorize('create', Event::class);
        $this->validate($request, [
            'name' => 'required',
            'date' => 'required',
            'start' => 'required',
            'end' => 'required',
            'hours' => 'required',
            'officer_id' => 'required'
        ]);
        $event = Event::create([
            'name' => $request->name,
            'date' => $request->date,
            'start' => $request->start,
            'end' => $request->end,
            'hours' => $request->hours,
            'officer_id' => $request->officer_id
        ]);
        return [
            'status' => 'success',
            'event' => $event
        ];
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function show(Event $event)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function edit(Event $event)
    {
        $this->authorize('update', $event);
        return view('event/edit', [
            'event' => $event,
            'members' => Member::all(),
            'officers' => Officer::all()
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Event $event)
    {
        $this->authorize('update', $event);
        $this->validate($request, [
            'name' => 'required',
            'date' => 'required',
            'start' => 'required',
            'end' => 'required',
            'hours' => 'required',
            'officer_id' => 'required'
        ]);
        $event->name = $request->name;
        $event->date = $request->date;
        $event->start = $request->start;
        $event->end = $request->end;
        $event->hours = $request->hours;
        $event->officer_id = $request->officer_id;
        if (count(array_filter($request->members)) != 0) {
            $members = array_filter($request->members);
            $members = Member::find($members);
            $event->members()->saveMany($members);
        }
        $event->save();
        $event->load('members');
        return [
            'status' => 'success',
            'event' => $event
        ];
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function destroy(Event $event)
    {
        $this->authorize('delete', $event);
    }
}

resources/views/event/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Create Event</div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST" action="{{route('events.store')}}">
                        {{ csrf_field() }}
                        <text-input label="Event Name" name="name" value="{{ old('name') }}" required></text-input>
                        <date-input label="Date" name="date" value="{{ old('date') }}" required></date-input>
                        <time-input label="Start Time" name="start" value="{{ old('start') }}" required></time-input>
                        <time-input label="End Time" name="end" value="{{ old('end') }}" required></time-input>
                        <text-input label="Hours" name="hours" value="{{ old('hours') }}" required></text-input>

                        <div class="form-group{{ $errors->has('officer_id') ? ' has-error' : '' }}">
                            <label for="officer_id" class="col-md-4 control-label">Officer</label>

                            <div class="col-md-6">
                                <select class="form-control" name="officer_id" required>
                                    <option disabled selected>Select Officer</option>
                                    @foreach($officers as $officer)
                                        <option value="{{ $officer->id }}">{{ $officer->member->first . " " . $officer->member->last }}</option>
                                    @endforeach
                                </select>
                                @if ($errors->has('officer_id'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('officer_id') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <submit-button btn-style="btn-success" label="Create"></submit-button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/event/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Edit Event</div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST" action="{{route('events.update', $event->id)}}">
                        {{ csrf_field() }}
                        {{ method_field('PUT') }}
                        <text-input label="Event Name" name="name" value="{{ old('name') . $event->name }}" required></text-input>
                        <date-input label="Date" name="date" value="{{ old('date') . $event->date }}" required></date-input>
                        <time-input label="Start Time" name="start" value="{{ old('start') . $event->start }}" required></time-input>
                        <time-input label="End Time" name="end" value="{{ old('end') . $event->end }}" required></time-input>
                        <text-input label="Hours" name="hours" value="{{ old('hours') . $event->hours }}" required></text-input>

                        <div class="form-group{{ $errors->has('officer_id') ? ' has-error' : '' }}">
                            <label for="officer_id" class="col-md-4 control-label">Officer</label>

                            <div class="col-md-6">
                                <select class="form-control" name="officer_id" required>
                                    <option disabled selected>Select Officer</option>
                                    @foreach($officers as $officer)
                                        <option value="{{ $officer->id }}">{{ $officer->member->first . " " . $officer->member->last }}</option>
                                    @endforeach
                                </select>
                                @if ($errors->has('officer_id'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('officer_id') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <data-list-input datalist="memberlist"></data-list-input>

                        <!-- <div class="form-group{{ $errors->has('members') ? ' has-error' : '' }}">
                            <label for="members" class="col-md-4 control-label">Event Members</label>

                            <div class="col-md-6">
                                <input name="members[]" type="text" list="memberlist"> -->
                                <datalist id="memberlist">
                                @foreach ($members as $member)
                                    <option value="{{$member->id}}">{{ $member->first . ' ' . $member->last }}</option>
                                @endforeach
                                </datalist>
                            <!-- </div>
                        </div> -->
                        <submit-button btn-style="btn-primary" label="Update"></submit-button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/event/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Event List</div>
                <div class="panel-body">
                    <table id="table" style="width: 100%">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Date</th>
                                <th>Start Time</th>
                                <th>End Time</th>
                                <th>Hours</th>
                                <th>Officer</th>
                                <th>Manage</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($events as $event)
                                <tr>
                                    <td>{{$event->id}}</td>
                                    <td>{{$event->name}}</td>
                                    <td>{{$event->date}}</td>
                                    <td>{{$event->start}}</td>
                                    <td>{{$event->end}}</td>
                                    <td>{{$event->hours}}</td>
                                    <td>{{$event->officer_id}}</td>
                                    <td><a class="btn btn-primary" href=" {{ route('events.edit', $event->id) }}">Manage</a></td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
<script>
    $(document).ready(function() {
        $('#table').DataTable();
    });
</script>
@endsection